const products = [
  {
    product_id: 0,
    image:
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=868&q=80",
    slug: "Hp-M234",
    brand: "HP",
    title: "HP M234",
    reviews: 4,
    desc: "Unleash productivity with our ultra-thin laptop. Packed with powerful features, this sleek device combines performance and portability seamlessly. ",
    price: 100000,
    category: "Laptop",
    featureProduct: true,
  },
  {
    product_id: 1,
    image:
      "https://images.unsplash.com/photo-1602080858428-57174f9431cf?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1251&q=80",
    slug: "Dell-M123",
    brand: "Dell",
    title: "Dell M123",
    reviews: 5,
    desc: "Immerse yourself in the gaming world with our high-performance gaming laptop. Featuring cutting-edge graphics, responsive controls.",
    price: 70000,
    category: "Laptop",
  },
  {
    product_id: 2,
    image:
      "https://images.unsplash.com/photo-1530893609608-32a9af3aa95c?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    slug: "Apple-3213",
    brand: "Apple",
    title: "Apple3213",
    reviews: 4,
    desc: "These laptops are designed for web browsing and cloud-based applications. They are affordable and easy to use.",
    price: 110000,
    category: "Laptop",
  },
  {
    product_id: 3,
    image:
      "https://images.unsplash.com/photo-1575024357670-2b5164f470c3?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    slug: "Aspiron-M867",
    brand: "Aspiron",
    title: "Aspiron M867",
    reviews: 3,
    desc: "These laptops are designed for business users. They have a durable design and security features.",
    price: 90000,
    category: "Laptop",
  },
  {
    product_id: 4,
    image:
      "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    slug: "HP-M0978",
    brand: "HP",
    title: "HP M0978",
    reviews: 5,
    desc: "Powerfull Laptop",
    price: 85000,
    category: "Laptop",
  },
  {
    product_id: 5,
    image:
      "https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=820&q=80",
    slug: "Dell-M987",
    brand: "Dell",
    title: "Dell M987",
    reviews: 4,
    desc: "These laptops are designed for portability. They are thin and light, and they have a long battery life.  ",
    price: 98500,
    category: "Laptop",
  },
  {
    product_id: 6,
    image:
      "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80",
    slug: "Nike-Powerful-Shoe",
    brand: "Nike",
    title: "Nike Shoe",
    reviews: 4,
    desc: "These shoes are designed to provproduct_ide comfort and support for long runs. They have a lightweight design and breathable materials.",
    price: 12000,
    category: "Shoes",
    newprice: 6000,
  },
  {
    product_id: 7,
    image:
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    slug: "Nike-fast-shoe",
    brand: "Nike",
    title: "Nike Shoe",
    reviews: 4,
    desc: "These shoes are designed for special occasions. They are made from high-quality materials and have a polished appearance.",
    price: 13500,
    category: "Shoes",
    featureProduct: true,
  },
  {
    product_id: 8,
    image:
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80",
    slug: "Sperry Men's Striper",
    brand: "Sperry",
    title: "Sperry Men's Striper",
    reviews: 4,
    desc: "Experience unmatched comfort and performance with our high-tech running shoes. Designed for athletes and fitness enthusiasts",
    price: 7000,
    category: "Shoes",
    featureProduct: true,
    newprice: 5500,
  },
  {
    product_id: 9,
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    slug: "Men's 669 V2 Walking Shoe",
    brand: "Balance",
    title: "Men's 669 V2 Walking Shoe",
    reviews: 4,
    desc: "Tackle New Terrain: Designed for stability and style, the 669v2 walking shoe from New Balance is a comfortable travel companion that’s always ready to go off-road",
    price: 8000,
    category: "Shoes",
  },
  {
    product_id: 10,
    image:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    slug: "Clarks Men's Tilden",
    brand: "Clarks",
    title: "Clarks Men's Tilden",
    reviews: 4,
    desc: "These shoes are designed for a variety of workouts, including cross-training, weightlifting, and plyometrics.",
    price: 6500,
    category: "Shoes",
    featureProduct: true,
  },
  {
    product_id: 11,
    image:
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-1.2.1&ixproduct_id=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    slug: "Under Armour Men's",
    brand: "Armour",
    title: "Under Armour Men's",
    reviews: 4,
    desc: "Lightweight mesh upper with 3-color digital print delivers complete breathability Durable leather overlays for stability",
    price: 7999,
    category: "Shoes",
    featureProduct: true,
  },
  {
    product_id: 12,
    image: "https://m.media-amazon.com/images/I/81zvCluMxQS._AC_UX385_.jpg",
    slug: "Champion T-Shirt",
    brand: "Nike",
    title: "Champion T-Shirt",
    reviews: 4,
    desc: "OFT AND DURABLE - Made of pure ringspun cotton, grown in the U.S., with a higher stitch count and reinforced shoulder seams for long life.",
    price: 1999,
    category: "Shirts",
  },
  {
    product_id: 13,
    image: "https://m.media-amazon.com/images/I/51wgCfk0CtL._AC_UX342_.jpg",
    slug: "Carhartt Men's",
    brand: "Carhartt",
    title: "Carhartt Carhartt Men's",
    reviews: 4,
    desc: "These are casual shirts that are made from cotton or a blend of cotton and polyester. They are comfortable and versatile.",
    price: 2500,
    category: "Shirts",
  },
  {
    product_id: 14,
    image: "https://m.media-amazon.com/images/I/81IQnaKr3FL._AC_UX342_.jpg",
    slug: "Men's Classic T-Shirt",
    brand: "Classic",
    title: "Classic T-Shirt",
    reviews: 4,
    desc: "SOFT COTTON TO FEEL GOOD ABOUT - Traceable, US-grown, ringspun cotton, produced using less water while yielding an ultra-soft feel.",
    price: 1500,
    category: "Shirts",
  },
  {
    product_id: 19,
    image: "https://m.media-amazon.com/images/I/91caRX7meaL._AC_SY500_.jpg",
    slug: "Men's Regular-Fit Long-Sleeve",
    brand: "Classic",
    title: " Men's Regular-Fit Long-Sleeve ",
    reviews: 4,
    desc: " Comfortable, easy fit through the shoulders, chest, and waist.A super soft cotton blend, knit in a waffle texture.",
    price: 1500,
    category: "Shirts",
  },
  {
    product_id: 14,
    image: "https://m.media-amazon.com/images/I/812A1DlgpQL._AC_SX569_.jpg",
    slug: "FORTRESS Garden Cricket Bat",
    brand: "Classic",
    title: "FORTRESS Garden Cricket Bat",
    reviews: 4,
    desc: "Manufactured with ultra-durable Fluro Yellow moulded plastic, provproduct_iding maximum longevity indoors & outdoors all year round.",
    price: 12000,
    category: "Sports",
    featureProduct: true,
  },
  {
    product_id: 15,
    image: "https://m.media-amazon.com/images/I/51+LL-SKHxL._AC_.jpg",
    slug: "SG Full Cricket Kit",
    brand: "Classic",
    title: "SG Full Cricket Kit",
    reviews: 5,
    desc: "SG CAMPUS FULL ACCESSORIES ENGLISH CRICKET KIT FULL SIZE",
    price: 30000,
    category: "Sports",
  },
  {
    product_id: 16,
    image:
      "https://m.media-amazon.com/images/I/51hJLKY+cDS._AC_PIcountsize-8,TopRight,0,0_SH20_.jpg",
    slug: "CW Bullet Right Hand Cricket Complete Kit",
    brand: "Classic",
    title: "CW Bullet Right Hand Cricket Complete Kit",
    reviews: 5,
    desc: "SG CAMPUS FULL ACCESSORIES ENGLISH CRICKET KIT FULL SIZE",
    price: 35000,
    category: "Sports",
  },
  {
    product_id: 17,
    image: "https://m.media-amazon.com/images/I/81uASlGnR9L._AC_SX569_.jpg",
    slug: "Franklin Sports NFL Youth Football Uniform Set",
    brand: "Classic",
    title: "Franklin Sports NFL Youth Football Uniform Set",
    reviews: 4.5,
    desc: "This kproduct_ids uniform set is the perfect gift for any young fan to dress up like their favorite NFL pros.",
    price: 5000,
    category: "Sports",
  },
  {
    product_id: 18,
    image:
      "https://m.media-amazon.com/images/I/71ao+rwcQeS._AC_SY300_SX300_.jpg",
    slug: "Select Classic V21 Soccer Ball",
    brand: "Classic",
    title: "Select Classic V21 Soccer Ball",
    reviews: 4.5,
    desc: "White V21 - 10-Ball - 	26 Inches",
    price: 15000,
    category: "Sports",
  },
];
export const categories = ["Laptops", "Shirts", "Sports", "Shoes"];

export default products;
